# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cde8744346067e4d0842900c83abb25bea0c2befab350da28a49a929a1ede651ad9e361bf1615e3d97bd434798f3d759c70a8ee5c9decc7c669b1d059cf355c1

test:
  secret_key_base: 64e20ec8b9d457efc8fd0d39eb6af9e58c175050f9830c0014d16981a6bacdbf86e69ae2274c5179225b76103860a4cf666930e4eb2d057760c67bd92d491619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
